### ISSUE TITLE
[공지] 하계 인턴십 프로그램 첫 모임 일정 

### ISSUE THREAD

**Issue by unizard** [sejong-rcv/2019.Summer.Intern#1]
## 모임 일정
- 장소: 지능기전공학부 회의실
- 시간: 6월 28일(금) 오후 시 30분

## R&D Admin의 준비
- 세종RCV 소개
  - 연구 철학, 연구 방향

## 멘토들의 발표 (@sejong-rcv/ur2019 )
-  지난 6개월의 기록 (부재: 나의 연구 성장기) 
-  발표 형식 없음, 발표 시간: 5분
-  자기 PR보다는 자신을 뒤돌아 보는 시간으로 활용하시길 바랍니다.

## 멘티들의 준비 
- 슬라이드 1~2장짜리 자기소개 
  - RCV 연구실 지원 이유를 포함
  - 앞으로 어떤 꿈을 가지고 있는지 내용 포함

**Comment by unizard** [comment]
@socome 지원아, 시간 될때 하계인턴십 친구들에게 7월 1일 첫 모임일자 공지해주렴. 그리고 본 repository watch 걸도록 안내 부탁한다. 오늘 교수님이 5인에게 문자 했는데, 아직 아무도 watch 안걸었거든? 시험기간이여서 그런거 같긴한데... 너가 다시 한번 watch 걸도록 안내해줘. 매번 전체 메일 보내는 것도 운영하는 사람들 입장에선 버거로운 일이뉘...

**Comment by socome** [comment]
@unizard 넵 단톡방 만들어서 진행하겠습니다.

**Comment by unizard** [comment]
@sejong-rcv/ur2019 @xown3197 @lini1634 @lini1634 @parkyeonjeong @lini1634 @함우빈

첫 모임 시간이 7월 1일(월)에서 6월 29일(금)로 변경되었습니다.
